services:
  db:
    image: postgres:15
    ports:
      - "5434:5432" # Host : Container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  web:
    build: .
    # This keeps the container running so you can enter it
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # <--- This maps /Dev/project/chat_to_order to /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CALENDAR_ID=${CALENDAR_ID}
    depends_on:
      - db

volumes:
  postgres_data:
